# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: pull_request


  
jobs:
  setup:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
          server-id: github 
          settings-path: ${{ github.workspace }} 
        
#      - name: Install Google Chrome
#        uses: browser-actions/setup-chrome@v1
#      - run: chrome --version
                          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

#      - name: Install Google Firefox
#        uses: browser-actions/setup-firefox@v1
#      - run: firefox --version

      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
#  build:
#    needs: setup
 #   runs-on: self-hosted
 #   steps:
#      - name: Execute task
#        run: ./gradlew clean build
     #- name: Validate Gradle wrapper
     # uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    
    #- name: Build with Gradle
     # uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      #with:
       # arguments: build
      - name: Execute Scenarios
        run: ./gradlew clean runTest -PcucumberOptions=@${GITHUB_REF##*/}

      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test run'
          description: 'Passed'
          state: 'success'
          sha: ${{github.event.pull_request.head.sha || github.sha}}
          target_url: simple-elf.github.io/github-allure-history/${{ github.run_number }}

    #- uses: actions/upload-artifact@v3
     # with:
      #  name: Cucumber Report
       # path: ./build/cucumber/reports/cucumber-html-reports
#
#    - name: Deploy report page
#      uses: peaceiris/actions-gh-pages@v3
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN }}
#        publish_dir: ./build/cucumber/reports/cucumber-html-reports

  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dbelyaev/action-checkstyle@v0.5.1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
