# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: "main"

  workflow_dispatch:
  
jobs:
  setup:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
          server-id: github 
          settings-path: ${{ github.workspace }} 
        
      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1
      - run: chrome --version
                          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Install Google Firefox
        uses: browser-actions/setup-firefox@v1
      - run: firefox --version
      
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Execute task
      run: ./gradlew clean build
     #- name: Validate Gradle wrapper
     # uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    
    #- name: Build with Gradle
     # uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      #with:
       # arguments: build
    - name: Execute Scenarios
      run: ./gradlew clean runTest -PcucumberOptions=@Test-1
      
    #- uses: actions/upload-artifact@v3
     # with:
      #  name: Cucumber Report
       # path: ./build/cucumber/reports/cucumber-html-reports
#
#    - name: Deploy report page
#      uses: peaceiris/actions-gh-pages@v3
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN }}
#        publish_dir: ./build/cucumber/reports/cucumber-html-reports
